server:
  port: 8087

spring:
  config:
    import: optional:secret.yaml
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    oauth2:
      client:
        movie-api:
          grantType: client_credentials
          #clientId:
          #clientSecret:
          #accessTokenUri:
          expireCorrectionInSeconds: 290
        registration:
          movie-api:
            authorization-grant-type: client_credentials
            #client-id:
            #client-secret:
        ##provider:
          ##movie-api:
            ##token-uri:
  #datasource:
    #url:
    #username:
    #password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate-dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

spring-doc:
  packages-to-scan: com.eri.controller
  api-docs:
    enabled: true
    path: /movie-api/api-docs
  swagger-ui:
    path: /movie-api/swagger-ui

movie-api:
  rest:
    uri: http://localhost:8089/movie-api/movies
  soap:
    default-uri: http://localhost:8085/movie-api/movies
    context-path: com.eri.generated.movieapi.stub

movie:
  list:
    file:
      url: src/main/resources/data/movies.json

auth:
  enabled: true
  ignored:
    urls: /movie-api/swagger-ui/**, /movie-api/api-docs, /movie-api/api-docs/*, /actuator/**

keycloak:
  ##auth-server-url:
  realm: movie-project
  resource: movie-app
  bearer-only: true
  use-resource-role-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, heapdump, threaddump, metrics

cache:
  clean:
    intervalInMilliseconds: 120000