server:
  port: 8087

movie-api:
  soap:
    default-uri: http://localhost:8085/movie-api/movies
    context-path: com.eri.generated.movieapi.stub

movie:
  list:
    file:
      url: src/main/resources/data/movies.json

keycloak:
  auth-server-url: https://lemur-14.cloud-iam.com/auth
  realm: movie-project
  resource: movie-app
  bearer-only: true
  use-resource-role-mappings: false