server:
  port: 8087

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

spring-doc:
  packages-to-scan: com.eri.controller
  api-docs:
    enabled: true
    path: /movie-api/api-docs
  swagger-ui:
    path: /movie-api/swagger-ui

movie-api:
  rest:
    uri: localhost:8089/movie-api/movies
  soap:
    default-uri: http://localhost:8085/movie-api/movies
    context-path: com.eri.generated.movieapi.stub

movie:
  list:
    file:
      url: src/main/resources/data/movies.json

auth:
  enabled: true
  ignored:
    urls: /movie-api/swagger-ui/**, /movie-api/api-docs, /movie-api/api-docs/*

keycloak:
  auth-server-url: https://lemur-14.cloud-iam.com/auth
  realm: movie-project
  resource: movie-app
  bearer-only: true
  use-resource-role-mappings: false

